### ISSUE TITLE
Update Triquetrum to Neon

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#104]
I attempted upgrading Triquetrum to Neon, but in the end there were problems and the update needed to be backed out.

Hudson was failing to download Gunnar's P2 repo.  See https://bugs.eclipse.org/bugs/show_bug.cgi?id=491951#c35 

The error message was:

``Caused by: org.eclipse.equinox.p2.core.ProvisionException: Communication with repository at https://eclipseguru.github.io/missing-swt-fragments failed.
	at org.eclipse.equinox.internal.p2.repository.CacheManager.createCache(CacheManager.java:202)
	at org.eclipse.tycho.p2.remote.RemoteRepositoryCacheManager.createCache(RemoteRepositoryCacheManager.java:66)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.getLocalFile(SimpleMetadataRepositoryFactory.java:66)
	at org.eclipse.equinox.internal.p2.metadata.repository.SimpleMetadataRepositoryFactory.load(SimpleMetadataRepositoryFactory.java:88)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.factoryLoad(MetadataRepositoryManager.java:57)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:768)
	at org.eclipse.equinox.internal.p2.repository.helpers.AbstractRepositoryManager.loadRepository(AbstractRepositoryManager.java:668)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryManager.loadRepository(MetadataRepositoryManager.java:96)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:61)
	at org.eclipse.tycho.p2.remote.RemoteMetadataRepositoryManager.loadRepository(RemoteMetadataRepositoryManager.java:53)
	at org.eclipse.tycho.p2.target.TargetDefinitionResolver$LoadedIULocation.loadRepository(TargetDefinitionResolver.java:288)
	... 28 more
Caused by: java.net.SocketTimeoutException: connect timed out`
``

Under Mac OS X and RHEL, mvn compile was complaining about:
``[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project org.eclipse.triquetrum.workflow.model: Compilation failure: Compilation failure:
[ERROR] /Users/cxh/git/triquetrum/org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/util/PtolemyUtil.java:[403]
[ERROR] ClassLoadingStrategy defaultClassLoadingStrategy = MoMLParser.getDefaultClassLoadingStrategy();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Type mismatch: cannot convert from org.ptolemy.osgi.ClassLoadingStrategy to org.ptolemy.classloading.ClassLoadingStrategy
[ERROR] /Users/cxh/git/triquetrum/org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/util/PtolemyUtil.java:[415]
[ERROR] importFilters.add(new RemoveGraphicalClassesForTriquetrum());
[ERROR] ^^^
[ERROR] The method add(MoMLFilter) in the type ArrayList<MoMLFilter> is not applicable for the arguments (RemoveGraphicalClassesForTriquetrum)
[ERROR] /Users/cxh/git/triquetrum/org.eclipse.triquetrum.workflow.model/src/main/java/org/eclipse/triquetrum/workflow/model/util/RemoveGraphicalClassesForTriquetrum.java:[13]
[ERROR] import ptolemy.moml.filter.RemoveGraphicalClasses;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import ptolemy.moml.filter.RemoveGraphicalClasses cannot be resolved 
``

Oddly, this also happens in the current head with Mars.1, after reverting the pull requests.

For this bug to be close, we need to upgrade Triquetrum to Neon so that the splash screen shows Neon instead of Mars and the binaries need to be created by Tycho on the Hudson Triquetrum site at [https://hudson.eclipse.org/triquetrum/job/triquetrum/](https://hudson.eclipse.org/triquetrum/job/triquetrum/).

In theory, the plan is to ship the Science2016 Release on Neon, so this has Science2016Release as a mile stone.

**Comment by cxbrooks** [comment]
Ok, I was able to build in my branch and get the installers for other platforms.

The key thing was to edit the top level pom.xml and remove 

`
<module>org.eclipse.triquetrum.dependencies</module>
`

However, I messed up the merge some how, so I reverted that pull request.

The issue was that the python work was not compiling.

While running mvn install, the error was:

```
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.eclipse.triquetrum.python.actor 1.0.0.qualifier
[ERROR]   Missing requirement: org.eclipse.triquetrum.scisoft.analysis.rpc 1.0.0 requires 'package org.apache.ws.commons.serialize 1.0.1' but it could not be found
[ERROR]   Cannot satisfy dependency: org.eclipse.triquetrum.python.actor 1.0.0.qualifier depends on: package org.eclipse.triquetrum.python.service 1.0.2
[ERROR]   Cannot satisfy dependency: org.eclipse.triquetrum.python.service 1.0.4 depends on: package org.eclipse.triquetrum.scisoft.analysis.rpc 0.0.0
```

**Comment by cxbrooks** [comment]
Triquetrum has been updated to use Neon and the Hudson build for Mac shows Neon in the splash screen and works.

We are using the swt fragments from Gunnar's P2 repo. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=491951#c35

For notes, see https://wiki.eclipse.org/Triquetrum/Target_Platform_Definition
