### ISSUE TITLE
Linux download fails to find modules

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#227]
The  Linux triquetrum distribution from https://hudson.eclipse.org/triquetrum/job/triquetrum/lastSuccessfulBuild/artifact/org.eclipse.triquetrum.repository/target/products/org.eclipse.triquetrum.workflow.editor.rcp.incubation-0.2.0.qualifier-linux.gtk.x86_64.tar.gz fails with a dialog that says to look for logs in the configs directory:

<img width="334" alt="screen shot 2017-04-23 at 8 52 27 pm" src="https://cloud.githubusercontent.com/assets/861991/25321905/0d00fd2c-2867-11e7-8c2c-78fa68b16c2a.png">

There are a number of log files.  triquetrum-0.2.0-SNAPSHOT/configuration/1493005876964.bak_0.log starts with:
```
!SESSION 2017-04-23 20:51:16.833 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.7.0_55
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64

!ENTRY org.eclipse.equinox.common 4 0 2017-04-23 20:51:18.116
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.equinox.common [264]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8))"

        at org.eclipse.osgi.container.Module.start(Module.java:444)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContaine\
r.java:1628)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContaine\
r.java:1608)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(Module\
Container.java:1579)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContaine\
r.java:1522)
        at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContaine\
r.java:1)
        at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
        at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)

!ENTRY org.eclipse.ant.core 4 0 2017-04-23 20:51:18.140
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: org.eclipse.ant.core [70]
  Unresolved requirement: Require-Bundle: org.eclipse.core.runtime; bundle-version="[3.2.0,4.0.0)"
    -> Bundle-SymbolicName: org.eclipse.core.runtime; bundle-version="3.13.0.v20170207-1030"; singleto\
n:="true"
       org.eclipse.core.runtime [90]
         Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=1.8)\
)"
         Unresolved requirement: Require-Bundle: org.eclipse.equinox.registry; bundle-version="[3.4.0,\
4.0.0)"; visibility:="reexport"
           -> Bundle-SymbolicName: org.eclipse.equinox.registry; bundle-version="3.7.0.v20170222-1344"\
; singleton:="true"
              org.eclipse.equinox.registry [311]
		Unresolved requirement: Import-Package: org.eclipse.core.runtime.jobs; resolution:="op\
tional"
                  -> Export-Package: org.eclipse.core.runtime.jobs; bundle-version="3.9.0.v20170223-17\
02"; bundle-symbolic-name="org.eclipse.core.jobs"; version="0.0.0"
                     org.eclipse.core.jobs [86]
```

Here are the log files:
[triquetrumLinuxLogs.tar.gz](https://github.com/eclipse/triquetrum/files/950385/triquetrumLinuxLogs.tar.gz)

**Comment by erwindl0** [comment]
I think this is due to the fact that you launch your RCP on a JDK 7 (cfr the 3rd line in the startup log).

Since Neon, Eclipse requires a JDK 8 to run on itself (although you can develop in it for Java 7 applications or older).

**Comment by cxbrooks** [comment]
Fixed!

I updated Triquetrum.product: -Dosgi.requiredJavaVersion=1.8

I verified that under Java 1.7, we get an error dialog:
<img width="399" alt="screen shot 2017-04-24 at 8 14 43 am" src="https://cloud.githubusercontent.com/assets/861991/25344228/51a058ce-28c6-11e7-8819-506f3a721aff.png">

The above dialog says:

```
Version 1.7.0_55 of the JVM is not suitable for
this product.  Version: 1.8 or greater is required
```
Closing.
