### ISSUE TITLE
ptolemy.actor.lib.Sinewave not found

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#291]
Under Mac and Linux, dragging the Sinewave actor in results no icon being created an the following appearing in the console:

```
Caused by: java.lang.ClassNotFoundException: ptolemy.actor.lib.Sinewave
	at org.ptolemy.classloading.osgi.OSGiClassLoadingStrategy.loadActorOrientedClass(OSGiClassLoadingStrategy.java:93)
	at org.eclipse.triquetrum.workflow.model.util.PtolemyUtil.loadActorOrientedClass(PtolemyUtil.java:491)
	at org.eclipse.triquetrum.workflow.model.util.PtolemyUtil._createEntity(PtolemyUtil.java:334)
	at org.eclipse.triquetrum.workflow.model.impl.EntityImpl.buildWrappedObject(EntityImpl.java:173)
	at org.eclipse.triquetrum.workflow.model.util.PtObjectBuilderAndApplierVisitor.visit(PtObjectBuilderAndApplierVisitor.java:20)
	at org.eclipse.triquetrum.workflow.model.impl.NamedObjImpl.welcome(NamedObjImpl.java:231)
	at org.eclipse.triquetrum.workflow.model.impl.EntityImpl.welcome(EntityImpl.java:182)
	at org.eclipse.triquetrum.workflow.model.impl.CompositeEntityImpl.welcome(CompositeEntityImpl.java:94)
	at org.eclipse.triquetrum.workflow.model.impl.CompositeActorImpl.welcome(CompositeActorImpl.java:66)
	at org.eclipse.triquetrum.workflow.editor.features.ModelElementCreateFeature.create(ModelElementCreateFeature.java:188)
	at org.eclipse.graphiti.features.impl.AbstractCreateFeature.execute(AbstractCreateFeature.java:100)
	at org.eclipse.graphiti.internal.command.GenericFeatureCommandWithContext.execute(GenericFeatureCommandWithContext.java:64)
	at org.eclipse.graphiti.internal.command.GFPreparableCommand.doExecute(GFPreparableCommand.java:37)
	at org.eclipse.emf.transaction.RecordingCommand.execute(RecordingCommand.java:135)
	at org.eclipse.graphiti.ui.internal.editor.GFWorkspaceCommandStackImpl.execute(GFWorkspaceCommandStackImpl.java:128)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:219)
	at org.eclipse.graphiti.internal.command.CommandExec.executeCommand(CommandExec.java:85)
	at org.eclipse.graphiti.ui.internal.command.CreateModelObjectCommand.execute(CreateModelObjectCommand.java:49)
	at org.eclipse.graphiti.ui.internal.editor.EmfOnGefCommand.execute(EmfOnGefCommand.java:54)
	at org.eclipse.graphiti.internal.command.GFPreparableCommand2.doExecute(GFPreparableCommand2.java:43)
	at org.eclipse.emf.transaction.RecordingCommand.execute(RecordingCommand.java:135)
	at org.eclipse.emf.workspace.EMFCommandOperation.doExecute(EMFCommandOperation.java:119)
	at org.eclipse.emf.workspace.AbstractEMFOperation.execute(AbstractEMFOperation.java:150)
	at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:488)
	at org.eclipse.emf.workspace.impl.WorkspaceCommandStackImpl.doExecute(WorkspaceCommandStackImpl.java:208)
	at org.eclipse.emf.transaction.impl.AbstractTransactionalCommandStack.execute(AbstractTransactionalCommandStack.java:165)
	at org.eclipse.graphiti.ui.internal.editor.GFWorkspaceCommandStackImpl.execute(GFWorkspaceCommandStackImpl.java:97)
	at org.eclipse.graphiti.ui.internal.editor.GFCommandStack.execute(GFCommandStack.java:138)
	at org.eclipse.graphiti.ui.internal.dnd.GFTemplateTransferDropTargetListener.handleDrop(GFTemplateTransferDropTargetListener.java:55)
	at org.eclipse.gef.dnd.AbstractTransferDropTargetListener.drop(AbstractTransferDropTargetListener.java:183)
	at org.eclipse.jface.util.DelegatingDropAdapter$3.run(DelegatingDropAdapter.java:219)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.JFaceUtil.lambda$0(JFaceUtil.java:44)
	at org.eclipse.jface.util.SafeRunnable.run(SafeRunnable.java:173)
	at org.eclipse.jface.util.DelegatingDropAdapter.drop(DelegatingDropAdapter.java:216)
	at org.eclipse.swt.dnd.DNDListener.handleEvent(DNDListener.java:91)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:86)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4257)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1502)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1525)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1510)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1314)
	at org.eclipse.swt.dnd.DropTarget.drop(DropTarget.java:723)
	at org.eclipse.swt.dnd.DropTarget.performDragOperation(DropTarget.java:737)
	at org.eclipse.swt.dnd.DropTarget.dropTargetProc(DropTarget.java:451)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:228)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1136)
	at org.eclipse.swt.widgets.Tree.mouseDownSuper(Tree.java:2144)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1128)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2616)
	at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2111)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5797)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:228)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2148)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2402)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5861)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5290)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5439)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3695)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1044)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:153)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:680)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:594)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:151)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1499)
```

**Comment by cxbrooks** [comment]
The installers are found at http://download.eclipse.org/triquetrum/0.2.0RC1/?d

**Comment by cxbrooks** [comment]
The Sinewave actor is also not found in the development setup.  So, the problem is not with the installers, but with Triquetrum in general.

**Comment by erwindl0** [comment]
Ok, not user-friendly indeed. This is because you didn't setup an AOC repository I guess.
Cfr https://wiki.eclipse.org/Triquetrum/Actor_Oriented_Classes#Setting_up_the_repository_with_the_Sinewave_AOC

We need to think about bootstrapping such a repo for the standard AOCs we want to be part of the distribution...

**Comment by erwindl0** [comment]
We'll get Sinewave contribution in order in the Ptolemy bundles first, file CQs for the changes, and deliver this in a patch release as a Xmas gift.

**Comment by erwindl0** [comment]
Prepared a Sinewave AOC provider in ptII SVN. 

After review with Christopher, I'll submit a new CQ for that one and we can get the SineWave in our palette then!

**Comment by erwindl0** [comment]
CQ created for the new Ptolemy AOC provider : https://dev.eclipse.org/ipzilla/show_bug.cgi?id=14783

**Comment by erwindl0** [comment]
This can be closed once the CQ is accepted.
