### ISSUE TITLE
org.eclipse.pde.core/.bundle_pool/Contents/Info.plist not found

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#351]
I'm working on updating to Bug #346 Update to Eclipse 2020-06.

I'm working in a branch: cxbrooks/enh/346/eclipse-2020-06-01

Following the instructions at http://wiki.eclipse.org/Triquetrum/Building_From_Sources, I check out the master, switch to the cxbrooks/enh/346/eclipse-2020-06-01 branch set the target and then run. 

After startup of Triquetrum, the console has:

 ```
 !ENTRY org.eclipse.urischeme 4 0 2020-08-29 08:57:56.749
  !MESSAGE file:/Users/cxh/eclipse-workspace-triq-0.4-5/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/Contents/Info.plist
  !STACK 0
  java.nio.file.NoSuchFileException: file:/Users/cxh/eclipse-workspace-triq-0.4-5/.metadata/.plugins/org.eclipse.pde.core/.bundle_pool/Contents/Info.plist
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at java.nio.file.Files.newBufferedReader(Files.java:2784)
	at java.nio.file.Files.newBufferedReader(Files.java:2816)
	at org.eclipse.urischeme.internal.registration.FileProvider.newReader(FileProvider.java:45)
	at org.eclipse.urischeme.internal.registration.RegistrationMacOsX.getPlistFileWriter(RegistrationMacOsX.java:123)
	at org.eclipse.urischeme.internal.registration.RegistrationMacOsX.changePlistFile(RegistrationMacOsX.java:140)
	at org.eclipse.urischeme.internal.registration.RegistrationMacOsX.handleSchemes(RegistrationMacOsX.java:54)
	at org.eclipse.urischeme.AutoRegisterSchemeHandlersJob.run(AutoRegisterSchemeHandlersJob.java:70)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)


```

**Comment by laeubi** [comment]
I would suggest to open a bug at eclipse platform as it seems the registration of URI schemes fails on your system . It seems the reader simply does not check if the file exits beforehand or is searching in the wrong place.
Even though this looks strange I would not expect any problems from this error.

**Comment by cxbrooks** [comment]
After updating the .view files (See 572cca790902157e9fab201cef87a0cc87a834cc), I can no longer reproduce this bug, so I'm closing.
