### ISSUE TITLE
Dragging a TrigFunction actor fails in the May 29 build and throws an exception in the head

### ISSUE THREAD

**Issue by cxbrooks** [eclipse/triquetrum#86]
Under Mac OS X, using the May 29 Triquetrum build, dragging a TrigFunction actor causes the Triquetrum process to go in to a busy loop, which requires killing the process.  Here is the stack trace obtained with jstack: [triqStack3.txt](https://github.com/eclipse/triquetrum/files/298502/triqStack3.txt)

In the development head, dragging a TrigFunction actor into the canvas works, but the following exception appears:

```
!ENTRY org.eclipse.ui 4 0 2016-06-03 15:49:30.263
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.ClassCastException: java.util.ArrayList cannot be cast to org.eclipse.gef.EditPart
	at org.eclipse.triquetrum.workflow.editor.palette.ui.PaletteTreeViewer.findObjectAtExcluding(PaletteTreeViewer.java:127)
	at org.eclipse.gef.tools.TargetingTool.updateTargetUnderMouse(TargetingTool.java:425)
	at org.eclipse.gef.tools.TargetingTool.unlockTargetEditPart(TargetingTool.java:388)
	at org.eclipse.gef.tools.SelectionTool.handleNativeDragFinished(SelectionTool.java:396)
	at org.eclipse.gef.tools.AbstractTool.nativeDragFinished(AbstractTool.java:1247)
	at org.eclipse.gef.EditDomain.nativeDragFinished(EditDomain.java:330)
	at org.eclipse.gef.ui.parts.DomainEventDispatcher.dispatchNativeDragFinished(DomainEventDispatcher.java:396)
	at org.eclipse.gef.ui.parts.GraphicalViewerImpl$1$TheLastListener.dragFinished(GraphicalViewerImpl.java:376)
	at org.eclipse.swt.dnd.DNDListener.handleEvent(DNDListener.java:45)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4230)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1491)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1514)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1499)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1299)
	at org.eclipse.swt.dnd.DragSource.draggedImage_endedAt_operation(DragSource.java:445)
	at org.eclipse.swt.dnd.DragSource.dragSourceProc(DragSource.java:562)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:227)
	at org.eclipse.swt.widgets.Widget.mouseDownSuper(Widget.java:1121)
	at org.eclipse.swt.widgets.Tree.mouseDownSuper(Tree.java:2047)
	at org.eclipse.swt.widgets.Widget.mouseDown(Widget.java:1113)
	at org.eclipse.swt.widgets.Control.mouseDown(Control.java:2569)
	at org.eclipse.swt.widgets.Tree.mouseDown(Tree.java:2015)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5692)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Widget.callSuper(Widget.java:227)
	at org.eclipse.swt.widgets.Widget.windowSendEvent(Widget.java:2130)
	at org.eclipse.swt.widgets.Shell.windowSendEvent(Shell.java:2337)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5756)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSendSuper(Native Method)
	at org.eclipse.swt.widgets.Display.applicationSendEvent(Display.java:5193)
	at org.eclipse.swt.widgets.Display.applicationProc(Display.java:5342)
	at org.eclipse.swt.internal.cocoa.OS.objc_msgSend(Native Method)
	at org.eclipse.swt.internal.cocoa.NSApplication.sendEvent(NSApplication.java:128)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3695)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1127)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1018)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:156)
	at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:654)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:337)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:598)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:139)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:380)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:235)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:669)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:608)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1515)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1488)
```

**Comment by cxbrooks** [comment]
In the devel head, after dragging in a TrigFunction actor, dragging in a SDFDirector causes the Triquetrum process to hang.

**Comment by cxbrooks** [comment]
I just verified that this is fixed in the June 4 build at https://hudson.eclipse.org/triquetrum/job/triquetrum/lastSuccessfulBuild/artifact/org.eclipse.triquetrum.repository/target/products/
